export const SELECT_LOCATION = "SELECT_LOCATION";
export const SELECT_SERVICE = "SELECT_SERVICE";
export const SELECT_MASTER = "SELECT_MASTER";
export const SELECT_TIME = "SELECT_TIME";
export const RESET_DATA = "RESET_DATA";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_CLIENT = "AUTH_CLIENT";

export const FETCH_LOCATIONS_START = "FETCH_LOCATIONS_START";
export const FETCH_LOCATIONS_SUCCESS = "FETCH_LOCATIONS_SUCCESS";
export const FETCH_LOCATIONS_FAIL = "FETCH_LOCATIONS_FAIL";

export const FETCH_SERVICES_START = "FETCH_SERVICES_START";
export const FETCH_SERVICES_SUCCESS = "FETCH_SERVICES_SUCCESS";
export const FETCH_SERVICES_FAIL = "FETCH_SERVICES_FAIL";

export const FETCH_MASTERS_START = "FETCH_MASTERS_START";
export const FETCH_MASTERS_SUCCESS = "FETCH_MASTERS_SUCCESS";
export const FETCH_MASTERS_FAIL = "FETCH_MASTERS_FAIL";

export const FETCH_RESERVATIONS_START = "FETCH_RESERVATIONS_START";
export const FETCH_RESERVATIONS_SUCCESS = "FETCH_RESERVATIONS_SUCCESS";
export const FETCH_RESERVATIONS_FAIL = "FETCH_RESERVATIONS_FAIL";

export const FETCH_TIME_AVAILABLE_START = "FETCH_TIME_AVAILABLE_START";
export const FETCH_TIME_AVAILABLE_SUCCESS = "FETCH_TIME_AVAILABLE_SUCCESS";
export const FETCH_TIME_AVAILABLE_FAIL = "FETCH_TIME_AVAILABLE_FAIL";

export const CHECK_PHONE_START = "CHECK_PHONE_START";
export const CHECK_PHONE_SUCCESS = "CHECK_PHONE_SUCCESS";
export const CHECK_PHONE_FAIL = "CHECK_PHONE_FAIL";

export const CHECK_RECEIVED_CODE_START = "CHECK_RECEIVED_CODE_START";
export const CHECK_RECEIVED_CODE_SUCCESS = "CHECK_RECEIVED_CODE_SUCCESS";
export const CHECK_RECEIVED_CODE_FAIL = "CHECK_RECEIVED_CODE_FAIL";

export const BOOKING_START = "BOOKING_START";
export const BOOKING_SUCCESS = "BOOKING_SUCCESS";
export const BOOKING_FAIL = "BOOKING_FAIL";
