export const SELECT_LOCATION = "SELECT_LOCATION";
export const SELECT_SERVICE = "SELECT_SERVICE";
export const SELECT_MASTER = "SELECT_MASTER";
export const SELECT_TIME = "SELECT_TIME";

export const FETCH_LOCATIONS_START = "FETCH_LOCATIONS_START";
export const FETCH_LOCATIONS_SUCCESS = "FETCH_LOCATIONS_SUCCESS";
export const FETCH_LOCATIONS_FAIL = "FETCH_LOCATIONS_FAIL";

export const FETCH_SERVICES_START = "FETCH_SERVICES_START";
export const FETCH_SERVICES_SUCCESS = "FETCH_SERVICES_SUCCESS";
export const FETCH_SERVICES_FAIL = "FETCH_SERVICES_FAIL";

export const FETCH_MASTERS_START = "FETCH_MASTERS_START";
export const FETCH_MASTERS_SUCCESS = "FETCH_MASTERS_SUCCESS";
export const FETCH_MASTERS_FAIL = "FETCH_MASTERS_FAIL";

export const FETCH_TIME_AVAILABLE_START = "FETCH_TIME_AVAILABLE_START";
export const FETCH_TIME_AVAILABLE_SUCCESS = "FETCH_TIME_AVAILABLE_SUCCESS";
export const FETCH_TIME_AVAILABLE_FAIL = "FETCH_TIME_AVAILABLE_FAIL";
